version: '3.9'

services:
    nodejs-server-development:
        build:
            context: ../../
            dockerfile: docker/development/Dockerfile
        image: nodejs-server-development
        container_name: nodejs-server-development
        volumes:
            - ./.env:/app/.env
            - ../../src:/app/src
        ports:
            - '4001:4000'
        links:
            - db
        depends_on:
            - db
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        healthcheck:
            test: [ "CMD-SHELL", "curl -f http://localhost:4001/" ]
            interval: 1m
            timeout: 3s
            start_period: 10s
            retries: 3
        restart: always
        networks:
            - development
    db:
        image: postgres:15
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 1m
            timeout: 5s
            start_period: 10s
            retries: 3
        networks:
            - development

networks:
    development:
        driver: bridge
